language: node_js
node_js:
- 8.9.0
cache:
  yarn: true
  directories:
  - node_modules
env:
  matrix:
  - CXX=g++-4.8
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
before_script:
- yarn install
script:
- yarn test
